BufferedJSONProcessor
th2-net/th2-data-services pull request #181
Opened 2022-10-27 13:13 UTC by 57R1D3R

CHANGE: v5/GetEvents, v5/GetMessages, v6/GetMessages switched to BufferedJSONProcessor

2022-10-31 04:54 UTC, ConnectDIY requested changes

2022-10-31 04:54 UTC, ConnectDIY commented on th2_data_services/provider/v5/commands/http.py
> +        source = partial(self.sse_handler.handle, partial(self.__handle_stream, data_source))
Forgot to return Data object

2022-10-31 04:54 UTC, ConnectDIY commented on th2_data_services/utils/json.py
> +            yield from self.from_buffer()
Docstrings required

2022-10-31 04:55 UTC, ConnectDIY commented
@xHacka add also release notes, please

2022-10-31 14:52 UTC, xHacka reviewed
Branch updated

2022-11-01 10:00 UTC, ConnectDIY approved these changes

2022-11-01 10:01 UTC, merged