metadata gets carried when using methods
th2-net/th2-data-services pull request #214
Opened 2023-01-12 11:39 UTC by xHacka

2023-01-12 11:50 UTC, xHacka commented
`def from_cache_file(cls, filename) -> "Data":`
Method will not save metadata of previous object.
Reason: Its a static method, which means it doesnt have access to previous object properties.

2023-01-12 12:10 UTC, xHacka commented
Should pages unittests be added to DS lib or LwDP?

2023-01-12 13:07 UTC, ConnectDIY requested changes

2023-01-12 13:07 UTC, ConnectDIY commented on th2_data_services/data.py
> +        self.metadata = metadata
It's common mistake to assign list or dict like this

When you do this, you assign a link to the object, but we need a deep copy.

2023-01-12 13:07 UTC, ConnectDIY commented on th2_data_services/data.py
> +        self.metadata = metadata
Let's also remake to `update_metadata` if you want to do it like a public method

2023-01-16 06:54 UTC, ConnectDIY approved these changes

2023-01-16 06:55 UTC, merged